variables:
  REGISTRY_IMAGE: blazorwebassembly
  CURDATE: $CI_COMMIT_TIMESTAMP
  IMAGENAME: $REGISTRY_IMAGE-$CI_COMMIT_TIMESTAMP

stages:          # List of stages for jobs, and their order of execution
  - build  
  - deploy

build_data_api_dev_image:
  image: docker:latest
  stage: build
  before_script:
    #- unset DOCKER_HOST
    - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD" $REGISTRY    
  script:
    - echo "$IMAGENAME"
    - cd ./My.BlazorWebAssembly
    #- docker build -f ./My.BlazorWebAssembly/Dockerfile --pull -t "$REGISTRY_IMAGE/data_store_api:develop" -f Dockerfile ..
    - echo "$REGISTRY_IMAGE/data_store_api:develop"
    - docker build -t "$IMAGENAME" -f ./My.BlazorWebAssembly/Dockerfile .
    - echo "Build step2 ..."
    - docker push "$IMAGENAME"
    - echo "Build step3 ..."

#
#  only:
#    refs:
#      - master
#    changes:
#      - My.BlazorWebAssembly/**/*

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
